---
title: "P1: Theme Project Pitch"
author: "Fabian Leon, Ram, Ashok"
output: pdf_document
---

## Introduction
Sorghum [Sorghum *bicolor* (L. Moench)] is the world's fifth most important cereal crop, in terms of both production and area planted. It is an increasingly relevant grain crop due to its resilience to drier and hotter climates. The United States is the world’s largest producer of grain sorghum, having produced 373 million bushels in 2020. Sorghum is typically grown in dryland areas from South Dakota to South Texas and Texas accounts for ~1.8 million of the United States' ~5.8 million acres of sorghum production. 

The idea for this visualization project is to use the [Texas A&M Variety Testing](http://varietytesting.tamu.edu/grainsorghum/) and [USDA NASS](https://quickstats.nass.usda.gov/) data repositories on [grain sorghum](https://www.sorghumcheckoff.com/sorghum-101/) production to visualize yield and production trends for the state of Texas. 

## Inspiration

Here we will embed 3-4 pictures of data visualizations that we think look good. 

## Sketch

Our sketch of what the final product will look like.
